services:
  app:
    image: ghcr.io/p-adamiec/free-games-claimer-remaster:${FGC_TAG:-latest}
    container_name: fgc-remaster
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "${NOVNC_PORT:-7080}:7080"
    volumes:
      - fgc_data:/fgc/data
      - ./main.py:/fgc/main.py
      - ./login_helper.py:/fgc/login_helper.py
      - ./src/core/config.py:/fgc/src/core/config.py
    env_file:
      - .env
    healthcheck:
      test: pgrep python3 && curl --fail http://localhost:7080 || exit 1
      interval: 10s
      timeout: 5s

volumes:
  fgc_data:
